AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AWS Serverless Jersey API - org.webservice.demo::Main
Resources:
  JerseyDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.webservice.demo.Main::handleRequest
      Runtime: java8
      CodeUri: build/libs/demo2-all.jar 
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any 

Outputs:
  JerseySampleApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/test/'
    Export:
      Name: demo
